version: '3'

services:
  kafka:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka_container
    volumes:
      - ./kafka_2.13-3.6.1:/app/kafka_2.13-3.6.1
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk
    command: sh -c "/app/kafka_2.13-3.6.1/bin/zookeeper-server-start.sh /app/kafka_2.13-3.6.1/config/zookeeper.properties"
